# Generated by Django 2.0.7 on 2019-02-19 14:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(limit_value=250, message='Сообщение должно быть длиной не более 250')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'молитвенная нужда',
                'verbose_name_plural': 'молитвенные нужды',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('youtube_link', models.CharField(max_length=200)),
                ('urgent_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст срочного объявления')),
                ('accept_prayer_request', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('interesting_event', models.BooleanField(default=False)),
                ('text_for_request', models.CharField(blank=True, help_text='Введите название для формы', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'видео',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('icon', models.FileField(blank=True, null=True, upload_to='video_categories')),
            ],
            options={
                'verbose_name': 'видео категория',
                'verbose_name_plural': 'видео категории',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.VideoCategory'),
        ),
    ]
