# Generated by Django 2.2 on 2019-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_link',
            field=models.CharField(help_text='Cсылка должна быть такого вида: https://www.youtube.com/embed/H0mkJVNmBpM', max_length=200),
        ),
    ]
