# Generated by Django 2.0.6 on 2018-06-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(null=True)),
                ('visible_in_menu', models.BooleanField(default=False)),
                ('seo_keywords', models.CharField(max_length=250)),
                ('seo_description', models.CharField(max_length=250)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
            options={
                'verbose_name': 'страница сайта',
                'verbose_name_plural': 'страницы сайта',
            },
        ),
    ]
