# Generated by Django 2.0.6 on 2018-06-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180628_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='seo_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
