# Generated by Django 2.0.6 on 2018-06-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_ministry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='icon',
            field=models.FileField(upload_to='ministries'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
