# Generated by Django 2.0.6 on 2018-07-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180704_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocategory',
            options={'verbose_name': 'видео категория', 'verbose_name_plural': 'видео категории'},
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
