# Generated by Django 2.0.6 on 2018-07-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180704_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
