# Generated by Django 2.0.7 on 2018-07-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
