# Generated by Django 2.0.7 on 2018-07-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20180710_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='uuid',
            field=models.UUIDField(blank=True, unique=True),
        ),
    ]
