# Generated by Django 2.0.7 on 2018-07-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_olduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olduser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='olduser',
            name='login',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
