# Generated by Django 2.0.7 on 2018-07-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20180713_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayerrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='PrayerRequest',
        ),
    ]
