# Generated by Django 2.0.7 on 2018-09-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20180718_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='interesting_event',
            field=models.BooleanField(default=False),
        ),
    ]
