# Generated by Django 2.0.7 on 2018-09-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_video_interesting_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ministry',
        ),
    ]
