# Generated by Django 2.0.7 on 2018-09-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_delete_ministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='video_categories'),
        ),
    ]
