# Generated by Django 2.0.7 on 2018-09-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_videocategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='text_for_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
