# Generated by Django 2.0.7 on 2018-09-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_video_text_for_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='urgent_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст срочного объявления'),
        ),
        migrations.AlterField(
            model_name='video',
            name='text_for_request',
            field=models.CharField(blank=True, help_text='Введите текст для формы, по умолчанию: Здесь вы можете оставить молитвенную записку, чтобы во время служения Церковь могла молится за Вашу нужду.', max_length=200, null=True),
        ),
    ]
