# Generated by Django 2.0.7 on 2018-09-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20180917_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='accept_prayer_request',
            field=models.BooleanField(default=False),
        ),
    ]
