# Generated by Django 2.0.7 on 2018-09-20 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20180918_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('emails', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('started', models.TimeField()),
                ('finished', models.TimeField(default=datetime.datetime(2018, 9, 20, 7, 53, 16, 657838, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылок',
            },
        ),
    ]
