# Generated by Django 2.0.7 on 2018-09-20 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_mailinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='finished',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
