# Generated by Django 2.0.7 on 2018-09-20 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20180920_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mailinglog',
            name='modified',
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='started',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
