# Generated by Django 2.0.7 on 2018-09-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20180920_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
