# Generated by Django 2.0.7 on 2018-11-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20180920_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='text_for_request',
            field=models.CharField(blank=True, help_text='Введите название для формы', max_length=200, null=True),
        ),
    ]
