# Generated by Django 2.0.7 on 2018-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20181108_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='cc_myself',
            field=models.BooleanField(default=False),
        ),
    ]
