# Generated by Django 2.0.7 on 2018-12-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20181109_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='cc_myself',
            field=models.BooleanField(),
        ),
    ]
