# Generated by Django 2.0.7 on 2019-02-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20181217_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='VideoCategory',
        ),
    ]
