# Generated by Django 2.0.7 on 2019-02-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20190219_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingLog',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
