# Generated by Django 2.0.6 on 2018-06-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='author',
        ),
    ]
