# Generated by Django 2.0.6 on 2018-06-19 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0004_auto_20180618_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 19, 7, 29, 54, 223076)),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
