# Generated by Django 2.0.6 on 2018-06-20 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0006_auto_20180620_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='newsevents.Author'),
        ),
    ]
