# Generated by Django 2.0.6 on 2018-06-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0007_newsitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
