# Generated by Django 2.0.6 on 2018-06-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0009_auto_20180621_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
