# Generated by Django 2.0.7 on 2018-09-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0013_auto_20180718_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-publication_date'], 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
