# Generated by Django 2.0.7 on 2018-10-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0014_auto_20180917_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(),
        ),
    ]
