# Generated by Django 2.0.7 on 2018-12-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0016_event_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
