# Generated by Django 2.0.6 on 2018-06-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('tel', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=30)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('img', models.FileField(upload_to='churches')),
            ],
            options={
                'verbose_name': 'церковь',
                'verbose_name_plural': 'церкви',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('city_img', models.FileField(upload_to='regions')),
            ],
            options={
                'verbose_name': 'регион',
                'verbose_name_plural': 'регионы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='church',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='churches.Region'),
        ),
    ]
