# Generated by Django 2.0.6 on 2018-06-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='tel',
            field=models.CharField(max_length=40),
        ),
    ]
