# Generated by Django 2.0.6 on 2018-06-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_auto_20180621_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='tel',
            field=models.CharField(max_length=50),
        ),
    ]
