# Generated by Django 2.0.6 on 2018-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0003_auto_20180621_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='lng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
