# Generated by Django 2.0.6 on 2018-06-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0005_auto_20180622_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='website',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
