# Generated by Django 2.0.7 on 2019-02-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
    ]
