# Generated by Django 2.0.6 on 2018-06-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20180626_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='galleries'),
        ),
    ]
