# Generated by Django 2.0.6 on 2018-06-27 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20180626_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photos',
        ),
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='galleries', to='galleries.Tag'),
        ),
    ]
