# Generated by Django 2.0.6 on 2018-06-28 03:41

from django.db import migrations, models
import galleries.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_auto_20180627_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='temp_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.FileField(default='', upload_to=galleries.models.gallery_upload_path_for_small),
            preserve_default=False,
        ),
    ]
