# Generated by Django 2.0.6 on 2018-06-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20180628_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
