# Generated by Django 2.0.7 on 2018-11-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0008_auto_20181108_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
