# Generated by Django 2.0.7 on 2019-02-19 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190219_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='description',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(limit_value=250, message='Сообщение должно быть длиной не более 250')]),
        ),
    ]
